<?php

namespace Duvg\ApiBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
}
